# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 手机号密码登陆获取token
POST {{host}}/auth8102/auth/login
Content-Type: application/json

{
  "phone": "18585131313",
  "password": "111111"
}
> {% client.global.set("auth_token", response.body.data.token); %}

###

# 退出登录
GET {{host}}/auth8102/logout
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# 根据userId查询用户
GET {{host}}/auth8102/user/11
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# 删除
GET {{host}}/auth8102/user/delete/12
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# 新增
POST {{host}}/auth8102/user/save
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "phone": "1111116",
  "password": "111111"
}

###

# 更新
POST {{host}}/auth8102/user/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 8,
  "phone": "1212121212",
  "password": "111111"
}

###

# 分页
GET {{host}}/auth8102/user/page?pageNum=1&pageSize=10&phone=185
Accept: application/json
Authorization: Bearer {{auth_token}}

###
