server:
  port: 8204
  servlet:
    context-path: /user8204

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ink.baojie.cloud.user8204api.bean.po
  executor-type: reuse
  global-config:
    db-config:
      table-prefix: t_
